// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYooPFP4cj6dnQCS3jL97BH6ps2bF7z-Q',
    appId: '1:190811687408:web:cf4f7cd71711591537b535',
    messagingSenderId: '190811687408',
    projectId: 'swd-project-eeb48',
    authDomain: 'swd-project-eeb48.firebaseapp.com',
    storageBucket: 'swd-project-eeb48.appspot.com',
    measurementId: 'G-344NT9JWY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFxiTbyneHVjQsakiLFiAWHSqCEA7pNv0',
    appId: '1:190811687408:android:6af1c1e6fa02f53337b535',
    messagingSenderId: '190811687408',
    projectId: 'swd-project-eeb48',
    storageBucket: 'swd-project-eeb48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYfwP28LWqgyLxW9DZHeRMTcFER0R4NUE',
    appId: '1:190811687408:ios:37c31c0f991ab7bc37b535',
    messagingSenderId: '190811687408',
    projectId: 'swd-project-eeb48',
    storageBucket: 'swd-project-eeb48.appspot.com',
    iosClientId:
        '190811687408-30thoqik2kv0mcqo6bsajrj3kj5q98v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundryMiddleTransportation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYfwP28LWqgyLxW9DZHeRMTcFER0R4NUE',
    appId: '1:190811687408:ios:96742b3035d31d8f37b535',
    messagingSenderId: '190811687408',
    projectId: 'swd-project-eeb48',
    storageBucket: 'swd-project-eeb48.appspot.com',
    iosClientId:
        '190811687408-egrd1al0mkr9fb3pldjs255d7tjefm6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundryMiddleTransportation.RunnerTests',
  );
}
